import React from 'react';
import { Link } from 'react-router-dom';
import { Segment, Button, Divider, Header, Label, Table } from 'semantic';

import screen from 'helpers/screen';
import { getToken, request } from 'utils/api';
import { parseToken } from 'utils/token';
import { withSession } from 'stores';

import { Layout } from 'components';
import LoadButton from 'components/LoadButton';
import ErrorMessage from 'components/ErrorMessage';
import { formatDateTime } from 'utils/date';

import Menu from './Menu';

@screen
@withSession
export default class Security extends React.Component {
  state = {
    error: null,
  };

  componentDidMount() {
    if (
      Date.parse(this.context.user.accessConfirmedAt) <
      Date.now() - 20 * 60 * 1000
    ) {
      this.props.history.push(
        `/confirm-access?to=${this.props.location.pathname}`
      );
    }
  }

  disableMFa = async () => {
    this.setState({ error: null });
    try {
      await request({
        method: 'DELETE',
        path: '/1/mfa/disable',
      });
      await this.context.bootstrap();
    } catch (e) {
      if (e.status === 403) {
        this.props.history.push(
          `/confirm-access?to=${this.props.location.pathname}`
        );
        return;
      } else {
        this.setState({ error: e });
      }
    }
  };

  logout = async (body) => {
    await request({
      method: 'POST',
      path: '/1/auth/logout',
      body,
    });
    await this.context.bootstrap();
  };

  render() {
    const { error } = this.state;
    const { mfaMethod, authTokens } = this.context.user;
    const { jti: currentJTi } = parseToken(getToken());

    return (
      <React.Fragment>
        <Menu />
        <Divider hidden />

        <Header>Two-factor authentication</Header>
        <p>
          After logging, you will be required to enter a code using one of the
          methods below. You can always set up more than one method later.
        </p>
        <Divider hidden></Divider>

        <Segment.Group>
          <Segment>
            <Layout horizontal spread>
              <div>
                <Header
                  size="tiny"
                  style={{ marginTop: 0, marginBottom: '0.5em' }}>
                  App authentication{' '}
                  {mfaMethod === 'otp' && <Label color="green">Enabled</Label>}
                </Header>
                <p>
                  Security codes will be generated by your preferred
                  authenticator app.
                </p>
              </div>
              <div>
                <Button
                  basic
                  size="small"
                  to="/settings/mfa-authenticator"
                  as={Link}>
                  {mfaMethod === 'otp' ? 'Config' : 'Enable'}
                </Button>
              </div>
            </Layout>
          </Segment>
          <Segment>
            <ErrorMessage error={error} />
            <Layout horizontal spread>
              <div>
                <Header
                  size="tiny"
                  style={{ marginTop: 0, marginBottom: '0.5em' }}>
                  SMS authentication
                  {mfaMethod == 'sms' && <Label color="green">Enabled</Label>}
                </Header>
                <p>
                  Security codes will be sent via SMS to your mobile device.
                </p>
              </div>
              <div>
                <Button basic size="small" to="/settings/mfa-sms" as={Link}>
                  {mfaMethod === 'sms' ? 'Config' : 'Enable'}
                </Button>
              </div>
            </Layout>
          </Segment>
        </Segment.Group>
        {mfaMethod && (
          <>
            <Divider hidden></Divider>
            <Segment color="red">
              <Layout horizontal spread>
                <div>
                  <Header
                    size="tiny"
                    style={{ marginTop: 0, marginBottom: '0.5em' }}>
                    Turn off two-factor authentication
                  </Header>
                  <p>
                    Turning off two-factor authentication will remove an extra
                    layer of security on your account.
                  </p>
                </div>
                <div>
                  <LoadButton
                    onClick={this.disableMFa}
                    basic
                    size="small"
                    color="red">
                    Turn off
                  </LoadButton>
                </div>
              </Layout>
            </Segment>
          </>
        )}
        <br />
        <br />
        <Header>Authenticated Sessions</Header>
        <Segment>
          <Table basic="very">
            <Table.Header>
              <Table.Row>
                <Table.HeaderCell>Device/Agent</Table.HeaderCell>
                <Table.HeaderCell>Ip</Table.HeaderCell>
                <Table.HeaderCell>Created At</Table.HeaderCell>
                <Table.HeaderCell>Action</Table.HeaderCell>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {authTokens.map((token) => {
                return (
                  <Table.Row key={token.id}>
                    <Table.Cell>
                      {token.userAgent || 'No User Agent provided'}{' '}
                      {token.jti === currentJTi && (
                        <Label horizontal>Current Session</Label>
                      )}
                    </Table.Cell>
                    <Table.Cell>{token.ip}</Table.Cell>
                    <Table.Cell>{formatDateTime(token.iat)}</Table.Cell>
                    <Table.Cell>
                      <LoadButton
                        disabled={token.jti === currentJTi}
                        basic
                        size="small"
                        onClick={() => this.logout({ jti: token.jti })}>
                        Logout
                      </LoadButton>
                    </Table.Cell>
                  </Table.Row>
                );
              })}
            </Table.Body>
          </Table>
        </Segment>
        <Button primary negative onClick={() => this.logout({ all: true })}>
          Logout all sessions
        </Button>
      </React.Fragment>
    );
  }
}
