import React from 'react';
import {
  Segment,
  Message,
  Form,
  Button,
  Divider,
  Header,
  Label,
} from 'semantic';
import { screen } from 'helpers';
import Menu from '../Menu';
import { request } from 'utils/api';

import { withSession } from 'stores';

@screen
@withSession
export default class Account extends React.Component {
  state = {
    user: this.context.user,
  };

  setField = (evt, { name, value }) => {
    this.setState({
      user: {
        ...this.state.user,
        [name]: value,
      },
    });
  };

  setCheckedField = (evt, { name, checked }) => {
    this.setField(evt, { name, value: checked });
  };

  async save() {
    const { user } = this.state;
    try {
      this.setState({
        loading: true,
        error: null,
      });
      const { data } = await request({
        method: 'PATCH',
        path: `/1/users/me`,
        body: user,
      });
      this.context.updateUser(data);
    } catch (error) {
      this.setState({
        error,
        loading: false,
      });
    }
  }

  render() {
    const { user, error, loading } = this.state;
    return (
      <React.Fragment>
        <Menu />
        <Divider hidden />
        {error && <Message error content={error.message} />}
        <Form onSubmit={() => this.save()}>
          <Header>Two-factor authentication</Header>
          <p>
            After logging, you will be required to enter a code using one of the
            methods below. You can always set up more than one method later.
          </p>
          <Divider hidden></Divider>

          <Segment.Group>
            <Segment>
              <Header size="tiny" style={{ marginTop: 0 }}>
                App authentication <Label color="green">Enabled</Label>
              </Header>
              Security codes will be generated by your preferred authenticator
              app.
            </Segment>
            <Segment>
              <Header size="tiny" style={{ marginTop: 0 }}>
                SMS authentication
              </Header>
              Security codes will be sent via SMS to your mobile device.
              <Button basic size="small">
                Set up
              </Button>
            </Segment>
          </Segment.Group>
          <Divider hidden></Divider>

          <Segment>
            <Header size="tiny" style={{ marginTop: 0 }}>
              Turn off two-factor authentication
            </Header>
            Turning off two-factor authentication will remove an extra layer of
            security on your account.
            <Button basic size="small">
              Turn off
            </Button>
          </Segment>
        </Form>
      </React.Fragment>
    );
  }
}
