#!/bin/bash

ZIP_FILE=$1
APP=$2

if [ "$ZIP_FILE" == "" ] || [ "$APP" == "" ]; then
cat <<-EOM

  Update icons from downloaded icomoon file.

  Usage: icomoon-import <ZIP_FILE> <APP>

EOM
exit 1
fi

unzip $ZIP_FILE symbol-defs.svg
mv symbol-defs.svg src/$APP/assets/icons.svg
rm $ZIP_FILE
