#!/usr/bin/env bash

# Note: To support docker this script cannot exist outside a
# directory with a package.json and must be copied over before
# yarn install from within the Dockerfile

dir="../../.githooks"
if [[ -d "$dir" ]]; then
  ln -sf "$dir/post-commit" "$dir/../.git/hooks/post-commit"
fi
