apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-mongo
  template:
    metadata:
      labels:
        app: backup-mongo
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-backup-mongo
          imagePullPolicy: Always
          name: main
          # resources:
          #   limits:
          #     cpu: "1000m"
          #     memory: "4Gi"
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_DB
              value: "bedrock_production"
            - name: BACKUPS_GS_BUCKET
              value: "bedrock-foundation-mongodb-backups"
