#!/usr/bin/env node

const { initialize } = require('../../src/utils/database');
const { createFixtures } = require('../../src/fixtures');

async function run() {
  await initialize();
  const result = await createFixtures();
  if (!result) {
    console.info('No DB fixtures to load, database is populated');
  }
}

run()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(`Fatal error: ${error.message}, exiting.`);
    console.error(error.stack);
    process.exit(1);
  });
