#!/usr/bin/env node

import logger from '@bedrockio/logger';
import { initialize } from '../../src/utils/database.js';
import { loadFixtures } from '../../src/utils/fixtures.js';

// Ensure models are loaded.
import '../../src/models/index.js';

(async () => {
  await initialize();
  const result = await loadFixtures();
  if (!result) {
    logger.info('No DB fixtures to load, database is populated');
  } else {
    logger.info('Done! Fixtures have been loaded.');
  }
  process.exit(0);
})();
