#!/usr/bin/env node

const { logger } = require('../../src/utils/logging');
const { initialize } = require('../../src/database');
const { createFixtures } = require('../../src/fixtures');

async function run() {
  await initialize();
  const result = await createFixtures();
  if (!result) {
    logger.info('No DB fixtures to load, database is populated');
  }
}

run()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    logger.error(`Fatal error: ${error.message}, exiting.`);
    console.warn(error.stack);
    process.exit(1);
  });
