#!/usr/bin/env node

const { logger } = require('@bedrockio/instrumentation');
const { initialize } = require('../../src/database');
const config = require('@bedrockio/config');
const { createFixtures } = require('../../src/fixtures');
const readline = require('readline');

const ENV_NAME = config.get('ENV_NAME');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const allowedEnvironments = ['test', 'development', 'staging'];

function prompt(message) {
  return new Promise((resolve) => {
    rl.question(message, (answer) => {
      resolve(answer);
      rl.close();
    });
  });
}

async function run() {
  if (!allowedEnvironments.includes(ENV_NAME)) {
    throw new Error(`Not allowed in ENV_NAME other than ${allowedEnvironments.join(', ')} (ENV_NAME=${ENV_NAME})`);
  }
  console.info(`
-------------------------------------------------------------------

  Warning: This will delete ALL DATA for the ${ENV_NAME} environment

-------------------------------------------------------------------

`);
  const answer = await prompt('Are you sure sure? [y|n] ');
  if (answer.toLowerCase() !== 'y') {
    throw new Error('Aborted');
  }
  const db = await initialize();
  console.info(`Dropping database...`);
  await db.dropDatabase();
  const result = await createFixtures();
  if (!result) {
    logger.info('No DB fixtures to load, database is populated');
  }
}

run()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    logger.error(`Fatal error: ${error.message}, exiting.`);
    console.warn(error.stack);
    process.exit(1);
  });
