apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-monitor
  template:
    metadata:
      labels:
        app: backup-monitor
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-backup-monitor
          imagePullPolicy: Always
          name: main
          # resources:
          #   limits:
          #     cpu: "1000m"
          #     memory: "4Gi"
          env:
            - name: GS_BUCKETS
              value: "bedrock-staging-uploads bedrock-staging-mongodb-backups"
            - name: POSTMARK_API_KEY
              value: "abc"
            - name: POSTMARK_FROM
              value: "admin@bedrock.foundation"
            - name: EMAIL_ALERT
              value: "admin@bedrock.foundation"
            - name: EMAIL_HEALTH_CHECK
              value: "admin@bedrock.foundation"
            - name: ENVIRONMENT
              value: "staging"
