import { useEffect, useState } from 'react';

import { useSession } from 'stores/session';

import ErrorMessage from 'components/ErrorMessage';
import { ExternalLink } from 'components/Link';
import QRCode from 'components/QRCode';

import { Button } from '@/components/ui/button';
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from '@/components/ui/input-otp';
import { Separator } from '@/components/ui/separator';
import { Spinner } from '@/components/ui/spinner';

import { request } from 'utils/api';

export default function Authenticator({ onClose, onSuccess }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [url, setUrl] = useState(null);
  const [secret, setSecret] = useState(null);
  const [code, setCode] = useState('');

  const { updateUser } = useSession();

  useEffect(() => {
    requestTOTP();
  }, []);

  async function requestTOTP() {
    try {
      setError(null);
      setLoading(true);
      const { data } = await request({
        method: 'POST',
        path: '/1/auth/totp/request',
      });
      setUrl(data.url);
      setSecret(data.secret);
      setLoading(false);
    } catch (err) {
      setError(err);
      setLoading(false);
    }
  }

  const handleCodeChange = (value) => {
    setCode(value);
  };

  const onSubmitCode = async () => {
    try {
      setError(null);
      setLoading(true);
      const { data } = await request({
        method: 'POST',
        path: '/1/auth/totp/enable',
        body: {
          code,
          secret,
        },
      });
      updateUser(data);
      onClose();
      onSuccess();
    } catch (err) {
      setError(err);
      setLoading(false);
    }
  };

  const renderQrCode = () => {
    if (url) {
      return (
        <QRCode
          data={url}
          style={{
            display: 'block',
          }}
        />
      );
    } else {
      return <Spinner className="size-6" />;
    }
  };

  return (
    <div className="flex flex-col gap-2">
      <p className="font-bold">1. Download an authenticator app.</p>
      <p className="text-sm">
        We recommend{' '}
        <ExternalLink href="https://support.google.com/accounts/answer/1066447">
          Google Authenticator
        </ExternalLink>
        ,{' '}
        <ExternalLink href="https://support.1password.com/one-time-passwords/">
          1Password
        </ExternalLink>
        , or <ExternalLink href="https://authy.com/">Authy.</ExternalLink>
      </p>
      <p className="font-bold">
        2. Scan this barcode using your authenticator app
      </p>
      <div className="flex justify-center py-4">{renderQrCode()}</div>
      <p className="font-bold">
        3. Enter the security code generated by your app
      </p>
      <ErrorMessage error={error} />
      <div className="flex items-center justify-center">
        <InputOTP
          maxLength={6}
          value={code}
          onChange={handleCodeChange}
          disabled={loading}>
          <InputOTPGroup>
            <InputOTPSlot index={0} />
            <InputOTPSlot index={1} />
            <InputOTPSlot index={2} />
            <InputOTPSlot index={3} />
            <InputOTPSlot index={4} />
            <InputOTPSlot index={5} />
          </InputOTPGroup>
        </InputOTP>
      </div>
      <Separator className="my-2" />
      <div className="flex gap-2">
        <Button onClick={onSubmitCode} disabled={loading || code.length !== 6}>
          {loading && <Spinner className="text-current" />}
          Verify
        </Button>
        <Button variant="outline" onClick={() => onClose()}>
          Cancel
        </Button>
      </div>
    </div>
  );
}
