// Serves assets with cache control headers and sane defaults.

import config from '@bedrockio/config';
import koaStatic from 'koa-static';

const SERVER_SOURCE_MAP_TOKEN = config.get('SERVER_SOURCE_MAP_TOKEN');

const DEBUG_COOKIE_NAME = 'debug';

export default function assetsMiddleware(path) {
  const serve = koaStatic(path, {
    index: false,
    // koa-static uses koa-send which takes this value in ms
    maxage: 365 * 24 * 60 * 60 * 1000,
    // Static assets always assume a hash in the URL (generated by vite),
    // so we can safely mark these objects as immutable here.
    immutable: true,
  });
  return async (ctx, next) => {
    if (isDisallowed(ctx)) {
      ctx.status = 404;
      return next();
    }
    await serve(ctx, next);
    if (!canCache(ctx)) {
      ctx.response.set('Cache-Control', 'no-cache');
    }
  };
}

function canCache(ctx) {
  if (ctx.status === 404 && !ctx.response.get('Cache-Control')) {
    // If no asset is found then explicitly pass no-cache to cloudflare.
    // This step is crucial to our rolling deploys as without it freshly
    // rolled out bundles will continue to 404 breaking the entire app.
    return false;
  }
  return !isSourceMap(ctx);
}

function isSourceMap(ctx) {
  return ctx.url.endsWith('.map');
}

function isDisallowed(ctx) {
  if (isSourceMap(ctx) && SERVER_SOURCE_MAP_TOKEN) {
    return ctx.cookies.get(DEBUG_COOKIE_NAME) !== SERVER_SOURCE_MAP_TOKEN;
  }

  return false;
}
