export default [
  {
    nameEn: 'Andorra',
    nameLocal: 'Andorra',
    countryCode: 'AD',
    callingCode: 376,
    flag: '🇦🇩',
  },
  {
    nameEn: 'Afghanistan',
    nameLocal:
      'د افغانستان اسلامي دولتدولت اسلامی افغانستان, جمهوری اسلامی افغانستان',
    countryCode: 'AF',
    callingCode: 93,
    flag: '🇦🇫',
  },
  {
    nameEn: 'Antigua and Barbuda',
    nameLocal: 'Antigua and Barbuda',
    countryCode: 'AG',
    callingCode: 1268,
    flag: '🇦🇬',
  },
  {
    nameEn: 'Anguilla',
    nameLocal: 'Anguilla',
    countryCode: 'AI',
    callingCode: 1264,
    flag: '🇦🇮',
  },
  {
    nameEn: 'Albania',
    nameLocal: 'Shqipëria',
    countryCode: 'AL',
    callingCode: 355,
    flag: '🇦🇱',
  },
  {
    nameEn: 'Armenia',
    nameLocal: 'Հայաստան',
    countryCode: 'AM',
    callingCode: 374,
    flag: '🇦🇲',
  },
  {
    nameEn: 'Angola',
    nameLocal: 'Angola',
    countryCode: 'AO',
    callingCode: 244,
    flag: '🇦🇴',
  },
  {
    nameEn: 'Antarctica',
    nameLocal: 'Antarctica, Antártico, Antarctique, Антарктике',
    countryCode: 'AQ',
    callingCode: 672,
    flag: '🇦🇶',
  },
  {
    nameEn: 'Argentina',
    nameLocal: 'Argentina',
    countryCode: 'AR',
    callingCode: 54,
    flag: '🇦🇷',
  },
  {
    nameEn: 'American Samoa',
    nameLocal: 'American Samoa',
    countryCode: 'AS',
    callingCode: 1684,
    flag: '🇦🇸',
  },
  {
    nameEn: 'Austria',
    nameLocal: 'Österreich',
    countryCode: 'AT',
    callingCode: 43,
    flag: '🇦🇹',
  },
  {
    nameEn: 'Australia',
    nameLocal: 'Australia',
    countryCode: 'AU',
    callingCode: 61,
    flag: '🇦🇺',
  },
  {
    nameEn: 'Aruba',
    nameLocal: 'Aruba',
    countryCode: 'AW',
    callingCode: 297,
    flag: '🇦🇼',
  },
  {
    nameEn: 'Åland Islands',
    nameLocal: 'Åland',
    countryCode: 'AX',
    callingCode: 358,
    flag: '🇦🇽',
  },
  {
    nameEn: 'Azerbaijan',
    nameLocal: 'Azərbaycan',
    countryCode: 'AZ',
    callingCode: 994,
    flag: '🇦🇿',
  },
  {
    nameEn: 'Bosnia and Herzegovina',
    nameLocal: 'Bosna i Hercegovina',
    countryCode: 'BA',
    callingCode: 387,
    flag: '🇧🇦',
  },
  {
    nameEn: 'Barbados',
    nameLocal: 'Barbados',
    countryCode: 'BB',
    callingCode: 1246,
    flag: '🇧🇧',
  },
  {
    nameEn: 'Bangladesh',
    nameLocal: 'গণপ্রজাতন্ত্রী বাংলাদেশ',
    countryCode: 'BD',
    callingCode: 880,
    flag: '🇧🇩',
  },
  {
    nameEn: 'Belgium',
    nameLocal: 'België, Belgique, Belgien',
    countryCode: 'BE',
    callingCode: 32,
    flag: '🇧🇪',
  },
  {
    nameEn: 'Burkina Faso',
    nameLocal: 'Burkina Faso',
    countryCode: 'BF',
    callingCode: 226,
    flag: '🇧🇫',
  },
  {
    nameEn: 'Bulgaria',
    nameLocal: 'България',
    countryCode: 'BG',
    callingCode: 359,
    flag: '🇧🇬',
  },
  {
    nameEn: 'Bahrain',
    nameLocal: 'البحرين',
    countryCode: 'BH',
    callingCode: 973,
    flag: '🇧🇭',
  },
  {
    nameEn: 'Burundi',
    nameLocal: 'Burundi',
    countryCode: 'BI',
    callingCode: 257,
    flag: '🇧🇮',
  },
  {
    nameEn: 'Benin',
    nameLocal: 'Bénin',
    countryCode: 'BJ',
    callingCode: 229,
    flag: '🇧🇯',
  },
  {
    nameEn: 'Saint Barthélemy',
    nameLocal: 'Saint-Barthélemy',
    countryCode: 'BL',
    callingCode: 590,
    flag: '🇧🇱',
  },
  {
    nameEn: 'Bermuda',
    nameLocal: 'Bermuda',
    countryCode: 'BM',
    callingCode: 1441,
    flag: '🇧🇲',
  },
  {
    nameEn: 'Brunei Darussalam',
    nameLocal: 'Brunei Darussalam',
    countryCode: 'BN',
    callingCode: 673,
    flag: '🇧🇳',
  },
  {
    nameEn: 'Bolivia (Plurinational State of)',
    nameLocal: 'Bolivia, Bulibiya, Volívia, Wuliwya',
    countryCode: 'BO',
    callingCode: 591,
    flag: '🇧🇴',
  },
  {
    nameEn: 'Bonaire, Sint Eustatius and Saba',
    nameLocal: 'Caribisch Nederland',
    countryCode: 'BQ',
    callingCode: 5997,
    flag: '🇧🇶',
  },
  {
    nameEn: 'Brazil',
    nameLocal: 'Brasil',
    countryCode: 'BR',
    callingCode: 55,
    flag: '🇧🇷',
  },
  {
    nameEn: 'Bhutan',
    nameLocal: 'འབྲུག་ཡུལ',
    countryCode: 'BT',
    callingCode: 975,
    flag: '🇧🇹',
  },
  {
    nameEn: 'Bouvet Island',
    nameLocal: 'Bouvetøya',
    countryCode: 'BV',
    callingCode: 47,
    flag: '🇧🇻',
  },
  {
    nameEn: 'Botswana',
    nameLocal: 'Botswana',
    countryCode: 'BW',
    callingCode: 267,
    flag: '🇧🇼',
  },
  {
    nameEn: 'Belarus',
    nameLocal: 'Беларусь',
    countryCode: 'BY',
    callingCode: 375,
    flag: '🇧🇾',
  },
  {
    nameEn: 'Belize',
    nameLocal: 'Belize',
    countryCode: 'BZ',
    callingCode: 501,
    flag: '🇧🇿',
  },
  {
    nameEn: 'Canada',
    nameLocal: 'Canada',
    countryCode: 'CA',
    callingCode: 1,
    flag: '🇨🇦',
  },
  {
    nameEn: 'Switzerland',
    nameLocal: 'Schweiz, Suisse, Svizzera, Svizra',
    countryCode: 'CH',
    callingCode: 41,
    flag: '🇨🇭',
  },
  {
    nameEn: "Côte d'Ivoire",
    nameLocal: "Côte d'Ivoire",
    countryCode: 'CI',
    callingCode: 225,
    flag: '🇨🇮',
  },
  {
    nameEn: 'Chile',
    nameLocal: 'Chile',
    countryCode: 'CL',
    callingCode: 56,
    flag: '🇨🇱',
  },
  {
    nameEn: 'Cameroon',
    nameLocal: 'Cameroun, Cameroon',
    countryCode: 'CM',
    callingCode: 237,
    flag: '🇨🇲',
  },
  {
    nameEn: 'China',
    nameLocal: '中国',
    countryCode: 'CN',
    callingCode: 86,
    flag: '🇨🇳',
  },
  {
    nameEn: 'Colombia',
    nameLocal: 'Colombia',
    countryCode: 'CO',
    callingCode: 57,
    flag: '🇨🇴',
  },
  {
    nameEn: 'Costa Rica',
    nameLocal: 'Costa Rica',
    countryCode: 'CR',
    callingCode: 506,
    flag: '🇨🇷',
  },
  {
    nameEn: 'Cuba',
    nameLocal: 'Cuba',
    countryCode: 'CU',
    callingCode: 53,
    flag: '🇨🇺',
  },
  {
    nameEn: 'Cabo Verde',
    nameLocal: 'Cabo Verde',
    countryCode: 'CV',
    callingCode: 238,
    flag: '🇨🇻',
  },
  {
    nameEn: 'Curaçao',
    nameLocal: 'Curaçao',
    countryCode: 'CW',
    callingCode: 599,
    flag: '🇨🇼',
  },
  {
    nameEn: 'Christmas Island',
    nameLocal: 'Christmas Island',
    countryCode: 'CX',
    callingCode: 61,
    flag: '🇨🇽',
  },
  {
    nameEn: 'Cyprus',
    nameLocal: 'Κύπρος, Kibris',
    countryCode: 'CY',
    callingCode: 357,
    flag: '🇨🇾',
  },
  {
    nameEn: 'Germany',
    nameLocal: 'Deutschland',
    countryCode: 'DE',
    callingCode: 49,
    flag: '🇩🇪',
  },
  {
    nameEn: 'Djibouti',
    nameLocal: 'Djibouti, جيبوتي, Jabuuti, Gabuutih',
    countryCode: 'DJ',
    callingCode: 253,
    flag: '🇩🇯',
  },
  {
    nameEn: 'Denmark',
    nameLocal: 'Danmark',
    countryCode: 'DK',
    callingCode: 45,
    flag: '🇩🇰',
  },
  {
    nameEn: 'Dominica',
    nameLocal: 'Dominica',
    countryCode: 'DM',
    callingCode: 767,
    flag: '🇩🇲',
  },
  {
    nameEn: 'Algeria',
    nameLocal: 'الجزائر',
    countryCode: 'DZ',
    callingCode: 213,
    flag: '🇩🇿',
  },
  {
    nameEn: 'Ecuador',
    nameLocal: 'Ecuador',
    countryCode: 'EC',
    callingCode: 593,
    flag: '🇪🇨',
  },
  {
    nameEn: 'Estonia',
    nameLocal: 'Eesti',
    countryCode: 'EE',
    callingCode: 372,
    flag: '🇪🇪',
  },
  {
    nameEn: 'Egypt',
    nameLocal: 'مصر',
    countryCode: 'EG',
    callingCode: 20,
    flag: '🇪🇬',
  },
  {
    nameEn: 'Western Sahara',
    nameLocal: 'Sahara Occidental',
    countryCode: 'EH',
    callingCode: 212,
    flag: '🇪🇭',
  },
  {
    nameEn: 'Eritrea',
    nameLocal: 'ኤርትራ, إرتريا, Eritrea',
    countryCode: 'ER',
    callingCode: 291,
    flag: '🇪🇷',
  },
  {
    nameEn: 'Spain',
    nameLocal: 'España',
    countryCode: 'ES',
    callingCode: 34,
    flag: '🇪🇸',
  },
  {
    nameEn: 'Ethiopia',
    nameLocal: 'ኢትዮጵያ, Itoophiyaa',
    countryCode: 'ET',
    callingCode: 251,
    flag: '🇪🇹',
  },
  {
    nameEn: 'Finland',
    nameLocal: 'Suomi',
    countryCode: 'FI',
    callingCode: 358,
    flag: '🇫🇮',
  },
  {
    nameEn: 'Fiji',
    nameLocal: 'Fiji',
    countryCode: 'FJ',
    callingCode: 679,
    flag: '🇫🇯',
  },
  {
    nameEn: 'Micronesia (Federated States of)',
    nameLocal: 'Micronesia',
    countryCode: 'FM',
    callingCode: 691,
    flag: '🇫🇲',
  },
  {
    nameEn: 'France',
    nameLocal: 'France',
    countryCode: 'FR',
    callingCode: 33,
    flag: '🇫🇷',
  },
  {
    nameEn: 'Gabon',
    nameLocal: 'Gabon',
    countryCode: 'GA',
    callingCode: 241,
    flag: '🇬🇦',
  },
  {
    nameEn: 'Grenada',
    nameLocal: 'Grenada',
    countryCode: 'GD',
    callingCode: 1473,
    flag: '🇬🇩',
  },
  {
    nameEn: 'Georgia',
    nameLocal: 'საქართველო',
    countryCode: 'GE',
    callingCode: 995,
    flag: '🇬🇪',
  },
  {
    nameEn: 'French Guiana',
    nameLocal: 'Guyane française',
    countryCode: 'GF',
    callingCode: 594,
    flag: '🇬🇫',
  },
  {
    nameEn: 'Guernsey',
    nameLocal: 'Guernsey',
    countryCode: 'GG',
    callingCode: 44,
    flag: '🇬🇬',
  },
  {
    nameEn: 'Ghana',
    nameLocal: 'Ghana',
    countryCode: 'GH',
    callingCode: 233,
    flag: '🇬🇭',
  },
  {
    nameEn: 'Gibraltar',
    nameLocal: 'Gibraltar',
    countryCode: 'GI',
    callingCode: 350,
    flag: '🇬🇮',
  },
  {
    nameEn: 'Greenland',
    nameLocal: 'Kalaallit Nunaat, Grønland',
    countryCode: 'GL',
    callingCode: 299,
    flag: '🇬🇱',
  },
  {
    nameEn: 'Guinea',
    nameLocal: 'Guinée',
    countryCode: 'GN',
    callingCode: 224,
    flag: '🇬🇳',
  },
  {
    nameEn: 'Guadeloupe',
    nameLocal: 'Guadeloupe',
    countryCode: 'GP',
    callingCode: 590,
    flag: '🇬🇵',
  },
  {
    nameEn: 'Equatorial Guinea',
    nameLocal: 'Guiena ecuatorial, Guinée équatoriale, Guiné Equatorial',
    countryCode: 'GQ',
    callingCode: 240,
    flag: '🇬🇶',
  },
  {
    nameEn: 'Greece',
    nameLocal: 'Ελλάδα',
    countryCode: 'GR',
    callingCode: 30,
    flag: '🇬🇷',
  },
  {
    nameEn: 'South Georgia and the South Sandwich Islands',
    nameLocal: 'South Georgia and the South Sandwich Islands',
    countryCode: 'GS',
    callingCode: 500,
    flag: '🇬🇸',
  },
  {
    nameEn: 'Guatemala',
    nameLocal: 'Guatemala',
    countryCode: 'GT',
    callingCode: 502,
    flag: '🇬🇹',
  },
  {
    nameEn: 'Guam',
    nameLocal: 'Guam, Guåhån',
    countryCode: 'GU',
    callingCode: 1,
    flag: '🇬🇺',
  },
  {
    nameEn: 'Guinea-Bissau',
    nameLocal: 'Guiné-Bissau',
    countryCode: 'GW',
    callingCode: 245,
    flag: '🇬🇼',
  },
  {
    nameEn: 'Guyana',
    nameLocal: 'Guyana',
    countryCode: 'GY',
    callingCode: 592,
    flag: '🇬🇾',
  },
  {
    nameEn: 'Hong Kong',
    nameLocal: '香港, Hong Kong',
    countryCode: 'HK',
    callingCode: 852,
    flag: '🇭🇰',
  },
  {
    nameEn: 'Honduras',
    nameLocal: 'Honduras',
    countryCode: 'HN',
    callingCode: 504,
    flag: '🇭🇳',
  },
  {
    nameEn: 'Croatia',
    nameLocal: 'Hrvatska',
    countryCode: 'HR',
    callingCode: 385,
    flag: '🇭🇷',
  },
  {
    nameEn: 'Haiti',
    nameLocal: 'Haïti, Ayiti',
    countryCode: 'HT',
    callingCode: 509,
    flag: '🇭🇹',
  },
  {
    nameEn: 'Hungary',
    nameLocal: 'Magyarország',
    countryCode: 'HU',
    callingCode: 36,
    flag: '🇭🇺',
  },
  {
    nameEn: 'Indonesia',
    nameLocal: 'Indonesia',
    countryCode: 'ID',
    callingCode: 62,
    flag: '🇮🇩',
  },
  {
    nameEn: 'Ireland',
    nameLocal: 'Ireland, Éire',
    countryCode: 'IE',
    callingCode: 353,
    flag: '🇮🇪',
  },
  {
    nameEn: 'Israel',
    nameLocal: 'ישראל',
    countryCode: 'IL',
    callingCode: 972,
    flag: '🇮🇱',
  },
  {
    nameEn: 'Isle of Man',
    nameLocal: 'Isle of Man',
    countryCode: 'IM',
    callingCode: 44,
    flag: '🇮🇲',
  },
  {
    nameEn: 'India',
    nameLocal: 'भारत, India',
    countryCode: 'IN',
    callingCode: 91,
    flag: '🇮🇳',
  },
  {
    nameEn: 'Iraq',
    nameLocal: 'العراق, Iraq',
    countryCode: 'IQ',
    callingCode: 964,
    flag: '🇮🇶',
  },
  {
    nameEn: 'Iran (Islamic Republic of)',
    nameLocal: 'ایران',
    countryCode: 'IR',
    callingCode: 98,
    flag: '🇮🇷',
  },
  {
    nameEn: 'Iceland',
    nameLocal: 'Ísland',
    countryCode: 'IS',
    callingCode: 354,
    flag: '🇮🇸',
  },
  {
    nameEn: 'Italy',
    nameLocal: 'Italia',
    countryCode: 'IT',
    callingCode: 39,
    flag: '🇮🇹',
  },
  {
    nameEn: 'Jersey',
    nameLocal: 'Jersey',
    countryCode: 'JE',
    callingCode: 44,
    flag: '🇯🇪',
  },
  {
    nameEn: 'Jamaica',
    nameLocal: 'Jamaica',
    countryCode: 'JM',
    callingCode: 876,
    flag: '🇯🇲',
  },
  {
    nameEn: 'Jordan',
    nameLocal: 'الأُرْدُن',
    countryCode: 'JO',
    callingCode: 962,
    flag: '🇯🇴',
  },
  {
    nameEn: 'Japan',
    nameLocal: '日本',
    countryCode: 'JP',
    callingCode: 81,
    flag: '🇯🇵',
  },
  {
    nameEn: 'Kenya',
    nameLocal: 'Kenya',
    countryCode: 'KE',
    callingCode: 254,
    flag: '🇰🇪',
  },
  {
    nameEn: 'Kyrgyzstan',
    nameLocal: 'Кыргызстан, Киргизия',
    countryCode: 'KG',
    callingCode: 996,
    flag: '🇰🇬',
  },
  {
    nameEn: 'Cambodia',
    nameLocal: 'កម្ពុជា',
    countryCode: 'KH',
    callingCode: 855,
    flag: '🇰🇭',
  },
  {
    nameEn: 'North Korea',
    nameLocal: '조선민주주의인민공화국',
    countryCode: 'KP',
    callingCode: 850,
    flag: '🇰🇵',
  },
  {
    nameEn: 'South Korea',
    nameLocal: '대한민국',
    countryCode: 'KR',
    callingCode: 82,
    flag: '🇰🇷',
  },
  {
    nameEn: 'Kiribati',
    nameLocal: 'Kiribati',
    countryCode: 'KI',
    callingCode: 686,
    flag: '🇰🇮',
  },
  {
    nameEn: 'Saint Kitts and Nevis',
    nameLocal: 'Saint Kitts and Nevis',
    countryCode: 'KN',
    callingCode: 1869,
    flag: '🇰🇳',
  },
  {
    nameEn: 'Kuwait',
    nameLocal: 'الكويت',
    countryCode: 'KW',
    callingCode: 965,
    flag: '🇰🇼',
  },
  {
    nameEn: 'Kazakhstan',
    nameLocal: 'Қазақстан, Казахстан',
    countryCode: 'KZ',
    callingCode: 7,
    flag: '🇰🇿',
  },
  {
    nameEn: 'Lebanon',
    nameLocal: 'لبنان, Liban',
    countryCode: 'LB',
    callingCode: 961,
    flag: '🇱🇧',
  },
  {
    nameEn: 'Saint Lucia',
    nameLocal: 'Saint Lucia',
    countryCode: 'LC',
    callingCode: 1758,
    flag: '🇱🇨',
  },
  {
    nameEn: 'Liechtenstein',
    nameLocal: 'Liechtenstein',
    countryCode: 'LI',
    callingCode: 423,
    flag: '🇱🇮',
  },
  {
    nameEn: 'Sri Lanka',
    nameLocal: 'ශ්‍රී ලංකා, இலங்கை',
    countryCode: 'LK',
    callingCode: 94,
    flag: '🇱🇰',
  },
  {
    nameEn: 'Liberia',
    nameLocal: 'Liberia',
    countryCode: 'LR',
    callingCode: 231,
    flag: '🇱🇷',
  },
  {
    nameEn: 'Lesotho',
    nameLocal: 'Lesotho',
    countryCode: 'LS',
    callingCode: 266,
    flag: '🇱🇸',
  },
  {
    nameEn: 'Lithuania',
    nameLocal: 'Lietuva',
    countryCode: 'LT',
    callingCode: 370,
    flag: '🇱🇹',
  },
  {
    nameEn: 'Luxembourg',
    nameLocal: 'Lëtzebuerg, Luxembourg, Luxemburg',
    countryCode: 'LU',
    callingCode: 352,
    flag: '🇱🇺',
  },
  {
    nameEn: 'Latvia',
    nameLocal: 'Latvija',
    countryCode: 'LV',
    callingCode: 371,
    flag: '🇱🇻',
  },
  {
    nameEn: 'Libya',
    nameLocal: 'ليبيا',
    countryCode: 'LY',
    callingCode: 218,
    flag: '🇱🇾',
  },
  {
    nameEn: 'Morocco',
    nameLocal: 'Maroc, ⵍⵎⵖⵔⵉⴱ, المغرب',
    countryCode: 'MA',
    callingCode: 212,
    flag: '🇲🇦',
  },
  {
    nameEn: 'Monaco',
    nameLocal: 'Monaco',
    countryCode: 'MC',
    callingCode: 377,
    flag: '🇲🇨',
  },
  {
    nameEn: 'Montenegro',
    nameLocal: 'Crna Gora, Црна Гора',
    countryCode: 'ME',
    callingCode: 382,
    flag: '🇲🇪',
  },
  {
    nameEn: 'Saint Martin (French part)',
    nameLocal: 'Saint-Martin',
    countryCode: 'MF',
    callingCode: 590,
    flag: '🇲🇫',
  },
  {
    nameEn: 'Madagascar',
    nameLocal: 'Madagasikara, Madagascar',
    countryCode: 'MG',
    callingCode: 261,
    flag: '🇲🇬',
  },
  {
    nameEn: 'Mali',
    nameLocal: 'Mali',
    countryCode: 'ML',
    callingCode: 223,
    flag: '🇲🇱',
  },
  {
    nameEn: 'Myanmar',
    nameLocal: 'မြန်မာ',
    countryCode: 'MM',
    callingCode: 95,
    flag: '🇲🇲',
  },
  {
    nameEn: 'Mongolia',
    nameLocal: 'Монгол Улс',
    countryCode: 'MN',
    callingCode: 976,
    flag: '🇲🇳',
  },
  {
    nameEn: 'Macao',
    nameLocal: '澳門, Macau',
    countryCode: 'MO',
    callingCode: 853,
    flag: '🇲🇴',
  },
  {
    nameEn: 'Martinique',
    nameLocal: 'Martinique',
    countryCode: 'MQ',
    callingCode: 596,
    flag: '🇲🇶',
  },
  {
    nameEn: 'Mauritania',
    nameLocal: 'موريتانيا, Mauritanie',
    countryCode: 'MR',
    callingCode: 222,
    flag: '🇲🇷',
  },
  {
    nameEn: 'Montserrat',
    nameLocal: 'Montserrat',
    countryCode: 'MS',
    callingCode: 1664,
    flag: '🇲🇸',
  },
  {
    nameEn: 'Malta',
    nameLocal: 'Malta',
    countryCode: 'MT',
    callingCode: 356,
    flag: '🇲🇹',
  },
  {
    nameEn: 'Mauritius',
    nameLocal: 'Maurice, Mauritius',
    countryCode: 'MU',
    callingCode: 230,
    flag: '🇲🇺',
  },
  {
    nameEn: 'Maldives',
    nameLocal: '',
    countryCode: 'MV',
    callingCode: 960,
    flag: '🇲🇻',
  },
  {
    nameEn: 'Malawi',
    nameLocal: 'Malawi',
    countryCode: 'MW',
    callingCode: 265,
    flag: '🇲🇼',
  },
  {
    nameEn: 'Mexico',
    nameLocal: 'México',
    countryCode: 'MX',
    callingCode: 52,
    flag: '🇲🇽',
  },
  {
    nameEn: 'Malaysia',
    nameLocal: '',
    countryCode: 'MY',
    callingCode: 60,
    flag: '🇲🇾',
  },
  {
    nameEn: 'Mozambique',
    nameLocal: 'Mozambique',
    countryCode: 'MZ',
    callingCode: 258,
    flag: '🇲🇿',
  },
  {
    nameEn: 'Namibia',
    nameLocal: 'Namibia',
    countryCode: 'NA',
    callingCode: 264,
    flag: '🇳🇦',
  },
  {
    nameEn: 'New Caledonia',
    nameLocal: 'Nouvelle-Calédonie',
    countryCode: 'NC',
    callingCode: 687,
    flag: '🇳🇨',
  },
  {
    nameEn: 'Norfolk Island',
    nameLocal: 'Norfolk Island',
    countryCode: 'NF',
    callingCode: 672,
    flag: '🇳🇫',
  },
  {
    nameEn: 'Nigeria',
    nameLocal: 'Nigeria',
    countryCode: 'NG',
    callingCode: 234,
    flag: '🇳🇬',
  },
  {
    nameEn: 'Nicaragua',
    nameLocal: 'Nicaragua',
    countryCode: 'NI',
    callingCode: 505,
    flag: '🇳🇮',
  },
  {
    nameEn: 'Norway',
    nameLocal: 'Norge, Noreg',
    countryCode: 'NO',
    callingCode: 47,
    flag: '🇳🇴',
  },
  {
    nameEn: 'Nepal',
    nameLocal: '',
    countryCode: 'NP',
    callingCode: 977,
    flag: '🇳🇵',
  },
  {
    nameEn: 'Nauru',
    nameLocal: 'Nauru',
    countryCode: 'NR',
    callingCode: 674,
    flag: '🇳🇷',
  },
  {
    nameEn: 'Niue',
    nameLocal: 'Niue',
    countryCode: 'NU',
    callingCode: 683,
    flag: '🇳🇺',
  },
  {
    nameEn: 'New Zealand',
    nameLocal: 'New Zealand',
    countryCode: 'NZ',
    callingCode: 64,
    flag: '🇳🇿',
  },
  {
    nameEn: 'Oman',
    nameLocal: 'سلطنة عُمان',
    countryCode: 'OM',
    callingCode: 968,
    flag: '🇴🇲',
  },
  {
    nameEn: 'Panama',
    nameLocal: 'Panama',
    countryCode: 'PA',
    callingCode: 507,
    flag: '🇵🇦',
  },
  {
    nameEn: 'Peru',
    nameLocal: 'Perú',
    countryCode: 'PE',
    callingCode: 51,
    flag: '🇵🇪',
  },
  {
    nameEn: 'French Polynesia',
    nameLocal: 'Polynésie française',
    countryCode: 'PF',
    callingCode: 689,
    flag: '🇵🇫',
  },
  {
    nameEn: 'Papua New Guinea',
    nameLocal: 'Papua New Guinea',
    countryCode: 'PG',
    callingCode: 675,
    flag: '🇵🇬',
  },
  {
    nameEn: 'Pakistan',
    nameLocal: 'پاکستان',
    countryCode: 'PK',
    callingCode: 92,
    flag: '🇵🇰',
  },
  {
    nameEn: 'Poland',
    nameLocal: 'Polska',
    countryCode: 'PL',
    callingCode: 48,
    flag: '🇵🇱',
  },
  {
    nameEn: 'Saint Pierre and Miquelon',
    nameLocal: 'Saint-Pierre-et-Miquelon',
    countryCode: 'PM',
    callingCode: 508,
    flag: '🇵🇲',
  },
  {
    nameEn: 'Pitcairn',
    nameLocal: 'Pitcairn',
    countryCode: 'PN',
    callingCode: 64,
    flag: '🇵🇳',
  },
  {
    nameEn: 'Puerto Rico',
    nameLocal: 'Puerto Rico',
    countryCode: 'PR',
    callingCode: 1,
    flag: '🇵🇷',
  },
  {
    nameEn: 'Palestine, State of',
    nameLocal: 'Palestinian Territory',
    countryCode: 'PS',
    callingCode: 970,
    flag: '🇵🇸',
  },
  {
    nameEn: 'Portugal',
    nameLocal: 'Portugal',
    countryCode: 'PT',
    callingCode: 351,
    flag: '🇵🇹',
  },
  {
    nameEn: 'Palau',
    nameLocal: 'Palau',
    countryCode: 'PW',
    callingCode: 680,
    flag: '🇵🇼',
  },
  {
    nameEn: 'Paraguay',
    nameLocal: 'Paraguay',
    countryCode: 'PY',
    callingCode: 595,
    flag: '🇵🇾',
  },
  {
    nameEn: 'Qatar',
    nameLocal: 'قطر',
    countryCode: 'QA',
    callingCode: 974,
    flag: '🇶🇦',
  },
  {
    nameEn: 'Réunion',
    nameLocal: 'La Réunion',
    countryCode: 'RE',
    callingCode: 262,
    flag: '🇷🇪',
  },
  {
    nameEn: 'Romania',
    nameLocal: 'România',
    countryCode: 'RO',
    callingCode: 40,
    flag: '🇷🇴',
  },
  {
    nameEn: 'Serbia',
    nameLocal: 'Србија',
    countryCode: 'RS',
    callingCode: 381,
    flag: '🇷🇸',
  },
  {
    nameEn: 'Russia',
    nameLocal: 'Россия',
    countryCode: 'RU',
    callingCode: 7,
    flag: '🇷🇺',
  },
  {
    nameEn: 'Rwanda',
    nameLocal: 'Rwanda',
    countryCode: 'RW',
    callingCode: 250,
    flag: '🇷🇼',
  },
  {
    nameEn: 'Saudi Arabia',
    nameLocal: 'السعودية',
    countryCode: 'SA',
    callingCode: 966,
    flag: '🇸🇦',
  },
  {
    nameEn: 'Solomon Islands',
    nameLocal: 'Solomon Islands',
    countryCode: 'SB',
    callingCode: 677,
    flag: '🇸🇧',
  },
  {
    nameEn: 'Seychelles',
    nameLocal: 'Seychelles',
    countryCode: 'SC',
    callingCode: 248,
    flag: '🇸🇨',
  },
  {
    nameEn: 'Sweden',
    nameLocal: 'Sverige',
    countryCode: 'SE',
    callingCode: 46,
    flag: '🇸🇪',
  },
  {
    nameEn: 'Singapore',
    nameLocal: 'Singapore',
    countryCode: 'SG',
    callingCode: 65,
    flag: '🇸🇬',
  },
  {
    nameEn: 'Saint Helena, Ascension and Tristan da Cunha',
    nameLocal: 'Saint Helena',
    countryCode: 'SH',
    callingCode: 290,
    flag: '🇸🇭',
  },
  {
    nameEn: 'Slovenia',
    nameLocal: 'Slovenija',
    countryCode: 'SI',
    callingCode: 386,
    flag: '🇸🇮',
  },
  {
    nameEn: 'Svalbard and Jan Mayen',
    nameLocal: 'Svalbard and Jan Mayen',
    countryCode: 'SJ',
    callingCode: 4779,
    flag: '🇸🇯',
  },
  {
    nameEn: 'Slovakia',
    nameLocal: 'Slovensko',
    countryCode: 'SK',
    callingCode: 421,
    flag: '🇸🇰',
  },
  {
    nameEn: 'Sierra Leone',
    nameLocal: 'Sierra Leone',
    countryCode: 'SL',
    callingCode: 232,
    flag: '🇸🇱',
  },
  {
    nameEn: 'San Marino',
    nameLocal: 'San Marino',
    countryCode: 'SM',
    callingCode: 378,
    flag: '🇸🇲',
  },
  {
    nameEn: 'Senegal',
    nameLocal: 'Sénégal',
    countryCode: 'SN',
    callingCode: 221,
    flag: '🇸🇳',
  },
  {
    nameEn: 'Somalia',
    nameLocal: 'Somalia, الصومال',
    countryCode: 'SO',
    callingCode: 252,
    flag: '🇸🇴',
  },
  {
    nameEn: 'Suriname',
    nameLocal: 'Suriname',
    countryCode: 'SR',
    callingCode: 597,
    flag: '🇸🇷',
  },
  {
    nameEn: 'South Sudan',
    nameLocal: 'South Sudan',
    countryCode: 'SS',
    callingCode: 211,
    flag: '🇸🇸',
  },
  {
    nameEn: 'Sao Tome and Principe',
    nameLocal: 'São Tomé e Príncipe',
    countryCode: 'ST',
    callingCode: 239,
    flag: '🇸🇹',
  },
  {
    nameEn: 'El Salvador',
    nameLocal: 'El Salvador',
    countryCode: 'SV',
    callingCode: 503,
    flag: '🇸🇻',
  },
  {
    nameEn: 'Sint Maarten (Dutch part)',
    nameLocal: 'Sint Maarten',
    countryCode: 'SX',
    callingCode: 1721,
    flag: '🇸🇽',
  },
  {
    nameEn: 'Syrian Arab Republic',
    nameLocal: 'سوريا, Sūriyya',
    countryCode: 'SY',
    callingCode: 963,
    flag: '🇸🇾',
  },
  {
    nameEn: 'Chad',
    nameLocal: 'Tchad, تشاد',
    countryCode: 'TD',
    callingCode: 235,
    flag: '🇹🇩',
  },
  {
    nameEn: 'Togo',
    nameLocal: 'Togo',
    countryCode: 'TG',
    callingCode: 228,
    flag: '🇹🇬',
  },
  {
    nameEn: 'Thailand',
    nameLocal: 'ประเทศไทย',
    countryCode: 'TH',
    callingCode: 66,
    flag: '🇹🇭',
  },
  {
    nameEn: 'Tajikistan',
    nameLocal: ',',
    countryCode: 'TJ',
    callingCode: 992,
    flag: '🇹🇯',
  },
  {
    nameEn: 'Tokelau',
    nameLocal: 'Tokelau',
    countryCode: 'TK',
    callingCode: 690,
    flag: '🇹🇰',
  },
  {
    nameEn: 'Timor-Leste',
    nameLocal: "Timor-Leste, Timor Lorosa'e",
    countryCode: 'TL',
    callingCode: 670,
    flag: '🇹🇱',
  },
  {
    nameEn: 'Turkmenistan',
    nameLocal: 'Türkmenistan',
    countryCode: 'TM',
    callingCode: 993,
    flag: '🇹🇲',
  },
  {
    nameEn: 'Tunisia',
    nameLocal: 'تونس, Tunisie',
    countryCode: 'TN',
    callingCode: 216,
    flag: '🇹🇳',
  },
  {
    nameEn: 'Tonga',
    nameLocal: 'Tonga',
    countryCode: 'TO',
    callingCode: 676,
    flag: '🇹🇴',
  },
  {
    nameEn: 'Turkey',
    nameLocal: 'Türkiye',
    countryCode: 'TR',
    callingCode: 90,
    flag: '🇹🇷',
  },
  {
    nameEn: 'Trinidad and Tobago',
    nameLocal: 'Trinidad and Tobago',
    countryCode: 'TT',
    callingCode: 868,
    flag: '🇹🇹',
  },
  {
    nameEn: 'Tuvalu',
    nameLocal: 'Tuvalu',
    countryCode: 'TV',
    callingCode: 688,
    flag: '🇹🇻',
  },
  {
    nameEn: 'United Republic of Tanzania',
    nameLocal: 'Tanzania',
    countryCode: 'TZ',
    callingCode: 255,
    flag: '🇹🇿',
  },
  {
    nameEn: 'Ukraine',
    nameLocal: 'Україна',
    countryCode: 'UA',
    callingCode: 380,
    flag: '🇺🇦',
  },
  {
    nameEn: 'Uganda',
    nameLocal: 'Uganda',
    countryCode: 'UG',
    callingCode: 256,
    flag: '🇺🇬',
  },
  {
    nameEn: 'United States of America',
    nameLocal: 'United States of America',
    countryCode: 'US',
    callingCode: 1,
    flag: '🇺🇸',
  },
  {
    nameEn: 'Uruguay',
    nameLocal: 'Uruguay',
    countryCode: 'UY',
    callingCode: 598,
    flag: '🇺🇾',
  },
  {
    nameEn: 'Uzbekistan',
    nameLocal: '',
    countryCode: 'UZ',
    callingCode: 998,
    flag: '🇺🇿',
  },
  {
    nameEn: 'Saint Vincent and the Grenadines',
    nameLocal: 'Saint Vincent and the Grenadines',
    countryCode: 'VC',
    callingCode: 1784,
    flag: '🇻🇨',
  },
  {
    nameEn: 'Venezuela (Bolivarian Republic of)',
    nameLocal: 'Venezuela',
    countryCode: 'VE',
    callingCode: 58,
    flag: '🇻🇪',
  },
  {
    nameEn: 'Virgin Islands (British)',
    nameLocal: 'British Virgin Islands',
    countryCode: 'VG',
    callingCode: 1284,
    flag: '🇻🇬',
  },
  {
    nameEn: 'Virgin Islands (U.S.)',
    nameLocal: 'United States Virgin Islands',
    countryCode: 'VI',
    callingCode: 1340,
    flag: '🇻🇮',
  },
  {
    nameEn: 'Vietnam',
    nameLocal: 'Việt Nam',
    countryCode: 'VN',
    callingCode: 84,
    flag: '🇻🇳',
  },
  {
    nameEn: 'Vanuatu',
    nameLocal: 'Vanuatu',
    countryCode: 'VU',
    callingCode: 678,
    flag: '🇻🇺',
  },
  {
    nameEn: 'Wallis and Futuna',
    nameLocal: 'Wallis-et-Futuna',
    countryCode: 'WF',
    callingCode: 681,
    flag: '🇼🇫',
  },
  {
    nameEn: 'Samoa',
    nameLocal: 'Samoa',
    countryCode: 'WS',
    callingCode: 685,
    flag: '🇼🇸',
  },
  {
    nameEn: 'Yemen',
    nameLocal: 'اليَمَن',
    countryCode: 'YE',
    callingCode: 967,
    flag: '🇾🇪',
  },
  {
    nameEn: 'Mayotte',
    nameLocal: 'Mayotte',
    countryCode: 'YT',
    callingCode: 262,
    flag: '🇾🇹',
  },
  {
    nameEn: 'South Africa',
    nameLocal: 'South Africa',
    countryCode: 'ZA',
    callingCode: 27,
    flag: '🇿🇦',
  },
  {
    nameEn: 'Zambia',
    nameLocal: 'Zambia',
    countryCode: 'ZM',
    callingCode: 260,
    flag: '🇿🇲',
  },
  {
    nameEn: 'Zimbabwe',
    nameLocal: 'Zimbabwe',
    countryCode: 'ZW',
    callingCode: 263,
    flag: '🇿🇼',
  },
  {
    nameEn: 'Eswatini',
    nameLocal: 'Swaziland',
    countryCode: 'SZ',
    callingCode: 268,
    flag: '🇸🇿',
  },
  {
    nameEn: 'North Macedonia',
    nameLocal: 'Македонија',
    countryCode: 'MK',
    callingCode: 389,
    flag: '🇲🇰',
  },
  {
    nameEn: 'Philippines',
    nameLocal: 'Philippines',
    countryCode: 'PH',
    callingCode: 63,
    flag: '🇵🇭',
  },
  {
    nameEn: 'Netherlands',
    nameLocal: 'Nederland',
    countryCode: 'NL',
    callingCode: 31,
    flag: '🇳🇱',
  },
  {
    nameEn: 'United Arab Emirates',
    nameLocal: 'دولة الإمارات العربيّة المتّحدة',
    countryCode: 'AE',
    callingCode: 971,
    flag: '🇦🇪',
  },
  {
    nameEn: 'Republic of Moldova',
    nameLocal: 'Moldova, Молдавия',
    countryCode: 'MD',
    callingCode: 373,
    flag: '🇲🇩',
  },
  {
    nameEn: 'Gambia',
    nameLocal: 'The Gambia',
    countryCode: 'GM',
    callingCode: 220,
    flag: '🇬🇲',
  },
  {
    nameEn: 'Dominican Republic',
    nameLocal: 'República Dominicana',
    countryCode: 'DO',
    callingCode: 1,
    flag: '🇩🇴',
  },
  {
    nameEn: 'Sudan',
    nameLocal: 'السودان',
    countryCode: 'SD',
    callingCode: 249,
    flag: '🇸🇩',
  },
  {
    nameEn: "Lao People's Democratic Republic",
    nameLocal: 'ປະຊາຊົນລາວ',
    countryCode: 'LA',
    callingCode: 856,
    flag: '🇱🇦',
  },
  {
    nameEn: 'Taiwan, Province of China',
    nameLocal: 'Taiwan',
    countryCode: 'TW',
    callingCode: 886,
    flag: '🇹🇼',
  },
  {
    nameEn: 'Republic of the Congo',
    nameLocal: 'République du Congo',
    countryCode: 'CG',
    callingCode: 242,
    flag: '🇨🇬',
  },
  {
    nameEn: 'Czechia',
    nameLocal: 'Česká republika',
    countryCode: 'CZ',
    callingCode: 420,
    flag: '🇨🇿',
  },
  {
    nameEn: 'United Kingdom',
    nameLocal: 'Great Britain',
    countryCode: 'GB',
    callingCode: 44,
    flag: '🇬🇧',
  },
  {
    nameEn: 'Niger',
    nameLocal: 'Niger',
    countryCode: 'NE',
    callingCode: 227,
    flag: '🇳🇪',
  },
  {
    nameEn: 'Democratic Republic of the Congo',
    nameLocal: 'Democratic Republic of the Congo',
    countryCode: 'CD',
    callingCode: 243,
    flag: '🇨🇩',
  },
  {
    nameEn: 'Commonwealth of The Bahamas',
    nameLocal: 'Commonwealth of The Bahamas',
    countryCode: 'BS',
    callingCode: null,
    flag: '🇧🇸',
  },
  {
    nameEn: 'Cocos (Keeling) Islands',
    nameLocal: 'Pulu Kokos (Keeling)',
    countryCode: 'CC',
    callingCode: null,
    flag: '🇨🇨',
  },
  {
    nameEn: 'Central African Republic',
    nameLocal: 'République centrafricaine',
    countryCode: 'CF',
    callingCode: 236,
    flag: '🇨🇫',
  },
  {
    nameEn: 'Cook Islands',
    nameLocal: "Kūki 'Āirani",
    countryCode: 'CK',
    callingCode: 682,
    flag: '🇨🇰',
  },
  {
    nameEn: 'Falkland Islands',
    nameLocal: 'Falkland Islands',
    countryCode: 'FK',
    callingCode: 500,
    flag: '🇫🇰',
  },
  {
    nameEn: 'Faroe Islands',
    nameLocal: 'Færøerne',
    countryCode: 'FO',
    callingCode: 298,
    flag: '🇫🇴',
  },
  {
    nameEn: 'Territory of Heard Island and McDonald Islands',
    nameLocal: 'Territory of Heard Island and McDonald Islands',
    countryCode: 'HM',
    callingCode: 672,
    flag: '🇭🇲',
  },
  {
    nameEn: 'British Indian Ocean Territory',
    nameLocal: 'British Indian Ocean Territory',
    countryCode: 'IO',
    callingCode: 246,
    flag: '🇮🇴',
  },
  {
    nameEn: 'Comoros',
    nameLocal: 'Umoja wa Komori',
    countryCode: 'KM',
    callingCode: 269,
    flag: '🇰🇲',
  },
  {
    nameEn: 'Cayman Islands',
    nameLocal: 'Cayman Islands',
    countryCode: 'KY',
    callingCode: null,
    flag: '🇰🇾',
  },
  {
    nameEn: 'Republic of the Marshall Islands',
    nameLocal: 'Aolepān Aorōkin Ṃajeḷ',
    countryCode: 'MH',
    callingCode: 692,
    flag: '🇲🇭',
  },
  {
    nameEn: 'Commonwealth of the Northern Mariana Islands',
    nameLocal: 'Sankattan Siha Na Islas Mariånas',
    countryCode: 'MP',
    callingCode: null,
    flag: '🇲🇵',
  },
  {
    nameEn: 'Turks and Caicos Islands',
    nameLocal: 'Turks and Caicos Islands',
    countryCode: 'TC',
    callingCode: null,
    flag: '🇹🇨',
  },
  {
    nameEn: 'French Southern and Antarctic Lands',
    nameLocal: 'Terres australes et antarctiques françaises',
    countryCode: 'TF',
    callingCode: 672,
    flag: '🇹🇫',
  },
  {
    nameEn: 'United States Minor Outlying Islands',
    nameLocal: 'United States Minor Outlying Islands',
    countryCode: 'UM',
    callingCode: 246,
    flag: '🇺🇲',
  },
  {
    nameEn: 'Holy See',
    nameLocal: 'Sancta Sedes',
    countryCode: 'VA',
    callingCode: 39,
    flag: '🇻🇦',
  },
];
