#!/usr/bin/env node

const logger = require('@bedrockio/logger');
const { initialize } = require('../../src/utils/database');
const { generateDefinition, DEFINITION_FILE } = require('../../src/utils/openapi');

(async () => {
  await initialize();
  await generateDefinition();
  logger.info(`Generated: ${DEFINITION_FILE}`);
  process.exit(0);
})();
