#!/usr/bin/env node

import logger from '@bedrockio/logger';
import { initialize } from '../../src/utils/database.js';
import { generateDefinition, DEFINITION_FILE } from '../../src/utils/openapi.js';

(async () => {
  await initialize();
  await generateDefinition();
  logger.info(`Generated: ${DEFINITION_FILE}`);
  process.exit(0);
})();
