#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
PLATFORM_NAME=$(basename `pwd`)
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)

gcloud config set project $GCLOUD_PROJECT
gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
gcloud container clusters get-credentials $GCLOUD_KUBERNETES_CLUSTER_NAME
gcloud config set container/cluster $GCLOUD_KUBERNETES_CLUSTER_NAME
