#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
PLATFORM_NAME=$(basename `pwd`)
ENVIRONMENT=$1
SERVICE=$2
SUB_SERVICE=$3
TAG=${4:-latest}

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment> [keyword]"
  exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1
if [ $? -ne 0 ]; then
  exit 1
fi

export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)

if [ "$SUB_SERVICE" != "" ]; then
  IMAGES=`docker images | grep $PLATFORM_NAME | grep $TAG | awk '{print $1}' | grep "services-$SERVICE-$SUB_SERVICE$" | grep -v gcr.io`
elif [ "$SERVICE" != "" ]; then
  IMAGES=`docker images | grep $PLATFORM_NAME | grep $TAG | awk '{print $1}' | grep "services-$SERVICE$" | grep -v gcr.io`
else
  IMAGES=`docker images | grep $PLATFORM_NAME | grep $TAG | awk '{print $1}' | grep "services-"`
fi

for image in $IMAGES; do
  gcr_tag="gcr.io/$GCLOUD_PROJECT/$image:$TAG"
  echo "Pushing $gcr_tag"
  docker tag $image:$TAG $gcr_tag
  docker push $gcr_tag
done
