#!/bin/bash

FILE=$1
SIZE=$2
DIR=$3
COLOR=${4-none}


function show_usage {
  script=$(basename $0)
  echo "Pads an image with transparent pixels to be exact dimensions.
Format is inferred from the extension.
SIZE should be in the format WxH.
DIR can move the file to a different directory, otherwise the file
will be overwritten.
COLOR can be any color name or hex in format #ffffff (default transparent).

Requires imagemagick.

Usage:   $script <FILE> <SIZE> [DIR] [COLOR]
Example: $script image.jpg 1024x768

$1"
  exit 1
}

if [ "$FILE" == "" ]; then
  show_usage "<FILE> argument expected"
fi

if [ "$SIZE" == "" ]; then
  show_usage "<SIZE> argument expected"
fi

if [ "$DIR" == "" ]; then
  OUTPUT="$FILE"
else
  FILENAME="$(basename -- $FILE)"
  OUTPUT="$DIR/$FILENAME"
fi

# Note order of background is important
command="convert $FILE -background $COLOR -resize $SIZE -extent $SIZE -gravity center $OUTPUT"
echo "$command"
eval "$command"
