FROM debian:10.13-slim

RUN apt-get -y update --fix-missing
RUN apt-get -y install apt-transport-https ca-certificates gnupg
RUN apt-get -y install curl bash cron

RUN mkdir /workdir
WORKDIR /workdir

COPY ./bucket-backups/install_gcloud_sdk.sh /workdir
RUN ./install_gcloud_sdk.sh

ADD bucket-backups /workdir/

CMD ["./entrypoint.sh"]
