FROM node:16.13.0-alpine

# Note layers should be ordered from less to more likely to change.

# Update & install required packages
RUN apk add --update bash curl;

COPY scripts/install_githooks /service/scripts/install_githooks

# Install app dependencies
COPY package.json /service/package.json
COPY yarn.lock /service/yarn.lock
RUN cd /service; yarn install;

# Copy app source
COPY . /service

# Set work directory to /api
WORKDIR /service

EXPOSE 2200

CMD ["yarn", "start"
