minimumReleaseAge: 10080
trustLockfile: true
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@bedrockio/eslint-plugin@1.6.0'
  - '@eslint-react/ast@5.19.1'
  - '@eslint-react/core@5.19.1'
  - '@eslint-react/eslint-plugin@5.19.1'
  - '@eslint-react/eslint@5.19.1'
  - '@eslint-react/jsx@5.19.1'
  - '@eslint-react/shared@5.19.1'
  - '@eslint-react/var@5.19.1'
  - eslint-plugin-react-dom@5.19.1
  - eslint-plugin-react-jsx@5.19.1
  - eslint-plugin-react-naming-convention@5.19.1
  - eslint-plugin-react-rsc@5.19.1
  - eslint-plugin-react-web-api@5.19.1
  - eslint-plugin-react-x@5.19.1
