#!/bin/bash

DIR=$1
OUTPUT=$2

function show_usage {
  script=$(basename $0)
  echo "Creates a spritesheet from a directory of png files.
Format will be inferred from the extension.

Requires imagemagick.

Usage:   $script <DIR> <OUTPUT>
Example: $script images/ sprite.png

$1"
  exit 1
}

if [ "$DIR" == "" ]; then
  show_usage "<DIR> argument expected"
fi

if [ "$OUTPUT" == "" ]; then
  show_usage "<OUTPUT> argument expected"
fi

command="montage $DIR* -background none -geometry +0+0 -tile x1 $OUTPUT"
echo "$command"
eval "$command"
