FROM node:18.14.0-alpine

# Note layers should be ordered from less to more likely to change.

# Update & install required packages
RUN apk add --update bash curl;

# Set work directory
WORKDIR /service

COPY scripts/install_githooks scripts/install_githooks

# Install dependencies and store yarn cache
COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn install --frozen-lockfile

# Copy app source
COPY . .

# Set your port
ENV PORT 2300
18.14pose the port to outside world
EXPOSE 2300

# Start production server
CMD ["yarn", "start"]
