FROM node:12-alpine

ENV NODE_ENV production

COPY package.json /service/package.json
COPY yarn.lock /service/yarn.lock

# Update & install required packages
RUN apk add --update bash git make python g++ curl; \
  cd /service; \
  yarn install --frozen-lockfile; \
  yarn --force add bcrypt --build-from-source; \
  apk del python make g++


# Copy app source
COPY . /service

# Set work directory to /api
WORKDIR /service


CMD ["./scripts/jobs-entrypoint.sh"]
