FROM node:16.13.0-alpine

# Note layers should be ordered from less to more likely to change.

# Update & install required packages
RUN apk add --update bash curl;

# Set work directory
WORKDIR /service

COPY scripts/install_githooks scripts/install_githooks

# Install app dependencies
COPY package.json yarn.lock .
RUN yarn install

# Copy app source
COPY . .

# Set your port
ENV PORT 2300

# Expose the port to outside world
EXPOSE 2300

# Start production server
CMD ["yarn", "start"]
