minimumReleaseAge: 10080
trustLockfile: true
blockExoticSubdeps: true
allowBuilds:
  mongodb-memory-server: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@bedrockio/eslint-plugin@1.6.0'
