#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

./infrastructure/scripts/check_gcloud_config $ENVIRONMENT
if [ $? -ne 0 ]; then
  exit 1
fi
mkdir -p infrastructure/environments/$ENVIRONMENT/certificates
openssl genrsa -out infrastructure/environments/$ENVIRONMENT/certificates/domain.key
openssl req -new -key infrastructure/environments/$ENVIRONMENT/certificates/domain.key -out infrastructure/environments/$ENVIRONMENT/certificates/domain.csr
echo "CSR stored as infrastructure/environments/$ENVIRONMENT/certificates/domain.csr"
cat infrastructure/environments/$ENVIRONMENT/certificates/domain.csr
echo "Make sure to save your certificate chain as infrastructure/environments/$ENVIRONMENT/certificates/domain.crt"
