#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

./infrastructure/scripts/check_gcloud_config $ENVIRONMENT
if [ $? -ne 0 ]; then
  exit 1
fi

export $(grep -v '^#' infrastructure/environments/$ENVIRONMENT/env.conf | xargs)
gcloud compute ssl-certificates create \
$ENVIRONMENT-ssl \
--certificate infrastructure/environments/$ENVIRONMENT/certificates/domain.crt \
--private-key infrastructure/environments/$ENVIRONMENT/certificates/domain.key
