#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../..
PLATFORM_NAME=$(basename `pwd`)
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

./deployment/scripts/deploy $ENVIRONMENT api
./deployment/scripts/deploy $ENVIRONMENT web
