#!/bin/bash
source ./deployment/scripts/parse_opts
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../

ENVIRONMENT=$(parse_arg $1)
SERVICE=$(parse_arg $2)
SUB_SERVICE=$(parse_arg $3)

if [ "$ENVIRONMENT" == "" ]; then
cat <<-EOM
  Usage: deploy_info <environment> [service]

  Display deployment author, date, and git tag or ref.
EOM
exit 1
fi

if [ "$SERVICE" == "" ]; then
  SERVICES=$(deployment/scripts/services $2)
else
  SERVICES="$SERVICE"
fi


./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

function deploy_info() {
  c1=$(get_field "author" "Author")
  c2=$(get_field "date" "Date")
  c3=$(get_field "branch" "Branch")
  c4=$(get_field "git" "Ref")
  if [ "$2" != "" ]; then
    name="$1-$2"
  else
    name=$1
  fi
  info=$(kubectl get deployment $name-deployment -o jsonpath="$c1|$c2|$c3|$c4" --ignore-not-found)

  if [ "$info" != "" ]; then
    echo "------- Deploy Details ($1) -------"
    echo ""
    echo $info | tr "^" " " | tr "|" "\n"
    echo ""
    echo "------------------------------------"
    echo ""
  fi

}

function get_field() {
  echo "^$2: {.spec.template.metadata.annotations.$1}{'\n'}"
}

echo ""
for service in $SERVICES; do
  deploy_info $service $SUB_SERVICE
done
