#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../..
ENVIRONMENT=$1
SECRET_NAME=$2

if [ "$ENVIRONMENT" == "" ] || [ "$SECRET_NAME" == "" ]; then
cat <<-EOM
  Usage: get_secrets <environment> <secret-name>

  Set secrets to deployment/secrets
EOM
exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)

INFILE=deployment/secrets/$SECRET_NAME.txt
if [ ! -f $INFILE ]; then
  echo "No such file: $INFILE"
  exit 1
fi

kubectl delete secret $SECRET_NAME --ignore-not-found
kubectl create secret generic $SECRET_NAME --from-env-file=$INFILE

echo "Uploaded secrets from $INFILE"
rm -f $INFILE
echo "Deleted $INFILE"
