#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../..
PLATFORM_NAME=$(basename `pwd`)
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)

kubectl get ingress
kubectl get services
kubectl get nodes
kubectl get pods
