#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
PLATFORM_NAME=$(basename `pwd`)
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment> [keyword]"
  exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT
if [ $? -ne 0 ]; then
  exit 1
fi

DEPLOYMENT_SCRIPTS=`ls deployment/$ENVIRONMENT/services | grep deployment.yml`

function apply_service() {
  kubectl delete -f deployment/$ENVIRONMENT/services/$1
  kubectl create -f deployment/$ENVIRONMENT/services/$1
}

export $(cat deployment/$ENVIRONMENT/env.conf | xargs)

if [ "$2" != "" ]; then
  DEPLOYMENT_SCRIPTS=`ls deployment/$ENVIRONMENT/services | grep deployment.yml | grep $2`
fi

for deployment_script in $DEPLOYMENT_SCRIPTS; do
  echo "Applying $deployment_script"
  apply_service $deployment_script
done
