#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi
export $(cat deployment/$ENVIRONMENT/env.conf | xargs)
gsutil mb -l us-east1 gs://$GCLOUD_BUCKET_PREFIX-$GCLOUD_ENV_NAME-uploads/
gsutil mb -l us-east1 gs://$GCLOUD_BUCKET_PREFIX-$GCLOUD_ENV_NAME-mongodb-backups/
gsutil mb -l us-east1 gs://$GCLOUD_BUCKET_PREFIX-$GCLOUD_ENV_NAME-uploads-backup/
