#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1
BASE_SERVICE=$2
TAG=$3
SERVICE="$BASE_SERVICE-$TAG"

if [ "$ENVIRONMENT" == "" ] || [ "$SERVICE" == "" ] || [ "$TAG" == "" ]; then
cat <<-EOM
  Usage: delete_feature_branch <environment> <service> <tag>

  Deletes a feature branch created by create_feature_branch.

EOM
exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT
if [ $? -ne 0 ]; then
  exit 1
fi

export $(grep -v '^#' deployment/$ENVIRONMENT/env.conf | xargs)

kubectl delete service/$SERVICE
kubectl delete deployment/$SERVICE-deployment
./deployment/scripts/patch_ingress $BASE_SERVICE $TAG "remove"
