#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1
SERVICES=$(deployment/scripts/services $2)

if [ "$ENVIRONMENT" == "" ]; then
cat <<-EOM
  Usage: deploy_info <environment> [service]

  Display deployment author, date, and git tag or ref.
EOM
exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

function deploy_info() {
  c1=$(get_field "author" "Author")
  c2=$(get_field "date" "Date")
  c3=$(get_field "branch" "Branch")
  c4=$(get_field "git" "Ref")
  info=$(kubectl get deployment $1-deployment -o jsonpath="$c1|$c2|$c3|$c4" --ignore-not-found)

  if [ "$info" != "" ]; then
    echo "------- Deploy Details ($1) -------"
    echo ""
    echo $info | tr "^" " " | tr "|" "\n"
    echo ""
    echo "------------------------------------"
    echo ""
  fi

}

function get_field() {
  echo "^$2: {.spec.template.metadata.annotations.$1}{'\n'}"
}

echo ""
for service in $SERVICES; do
  deploy_info $service
done
