#!/bin/bash

function metadata() {
  author=$(git config user.name)
  date=$(date)
  fields="\"author\":\"$(git config user.name)\""
  fields="$fields,\"date\":\"$(date)\""
  fields="$fields,\"git\":\"$(tag)\""
  fields="$fields,\"branch\":\"$(git branch --show-current)\""
  echo "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{$fields}}}}}"
}

function tag() {
  tag=`git tag --points-at HEAD`
  if [ "$tag" == "" ]; then
    tag=`git rev-parse --short --verify HEAD`
  fi
  if [[ $(git diff --stat) != '' ]]; then
    tag="$tag-dirty"
  fi
  echo $tag
}

metadata
