#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1
SECRET_NAME=$2

if [ "$ENVIRONMENT" == "" ] || [ "$SECRET_NAME" == "" ]; then
cat <<-EOM
  Usage: get_secrets <environment> <secret-name>
  Fetch secrets to deployment/environments/<environment>/secrets
EOM
exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

export $(grep -v '^#' deployment/environments/$ENVIRONMENT/.env | xargs)

DATA=`kubectl get secret $SECRET_NAME -o json | jq -r '.data | keys[] as $k | "\($k):\(.[$k])"'`
mkdir -p deployment/environments/$ENVIRONMENT/secrets
OUTFILE=deployment/environments/$ENVIRONMENT/secrets/$SECRET_NAME.txt
echo -n "" > $OUTFILE
for line in $DATA; do
  KEY=`echo $line | cut -d ':' -f 1`
  VALUE=`echo $line | cut -d ':' -f 2 | base64 --decode`
  echo "$KEY=$VALUE" >> $OUTFILE
done

echo "Saved secret to $OUTFILE - make sure to REMOVE THE FILE once you've made your changes"
