#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
PLATFORM_NAME=$(basename `pwd`)
IMAGES=`docker images | grep $PLATFORM_NAME | awk '{print $1}'`
ENVIRONMENT=$1

if [ "$ENVIRONMENT" == "" ]; then
  echo "Usage: $0 <environment> [keyword]"
  exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT
if [ $? -ne 0 ]; then
  exit 1
fi

function push_service() {
  gcloud docker -- push gcr.io/$1/$2:latest
}

export $(cat deployment/$ENVIRONMENT/env.conf | xargs)

if [ "$2" != "" ]; then
  echo "Pushing all images matching $2"
  IMAGES=`docker images | grep $PLATFORM_NAME | awk '{print $1}' | grep $2 | grep -v gcr.io`
fi

for image in $IMAGES; do
  echo "Pushing $GCLOUD_PROJECT / $image"
  docker tag $image gcr.io/$GCLOUD_PROJECT/$image
  push_service $GCLOUD_PROJECT $image
done
