#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH; cd ../../
ENVIRONMENT=$1
CONFIGMAP_NAME=$2

if [ "$ENVIRONMENT" == "" ] || [ "$CONFIGMAP_NAME" == "" ]; then
cat <<-EOM
  Usage: set_configmap <environment> <configmap-name>
  Set configmap from deployment/environments/<environment>/configmaps
EOM
exit 1
fi

./deployment/scripts/check_gcloud_config $ENVIRONMENT 1

export $(grep -v '^#' deployment/environments/$ENVIRONMENT/env.conf | xargs)

INFILE=deployment/environments/$ENVIRONMENT/configmaps/$CONFIGMAP_NAME.conf
if [ ! -f $INFILE ]; then
  echo "No such file: $INFILE"
  exit 1
fi

kubectl create configmap $CONFIGMAP_NAME-config --from-env-file=$INFILE -o yaml --dry-run=client | kubectl apply -f -

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
LightBlue='\033[1;34m'
NC='\033[0m'

echo -e "${LightBlue}"
kubectl get cm/$CONFIGMAP_NAME-config -o yaml
echo ""
echo -e "${GREEN}Successfully set configmap '$CONFIGMAP_NAME-config' with '$INFILE'${NC}"
echo ""
echo -e "Re-deploy the following services:${YELLOW}"
grep -lr "name: $CONFIGMAP_NAME-config" ./deployment/environments/$ENVIRONMENT
echo ""
