#!/bin/bash

if [[ "$1" == "production" ]]; then
  read -d '' message << EOM
-------------------------------------------------------------------

                      Deploying to production!

-------------------------------------------------------------------
EOM
  message+=$'\nAre you sure? (y/n): '
  read -p "$message" -n 1 -r
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    echo ""
    echo "Aborted!"
    exit 1
  else
    echo ""
  fi
fi

